accounts/urls.py
from django.urls import path, include
from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

facebook/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index),
    path('accounts/', include('accounts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name="posts"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:id>/like/', views.like, name="like"),
]

accounts/models.py
from django.db import models

# Create your models here.

manytomany/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Patient(models.Model):
    name = models.CharField(max_length=100)
    doctors = models.ManyToManyField(Doctor, related_name='patients')
    def __str__(self):
        return self.name


# class Reservation(models.Model):
#     doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
#     patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
#     time = models.CharField(max_length=100)
#     location = models.CharField(max_length=100, default="3층")
#     def __str__(self):
#         return f"{self.doctor.name}의사 : {self.patient.name}환자"

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('posts:index')

manytomany/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)

def create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("posts:index")
    else:
        form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'posts/form.html', context)


def like(request, id):
    post = get_object_or_404(Post, id=id)
    user = request.user
    # if user in post.like_users.all():
    if user.like_posts.filter(id=id):
        user.like_posts.remove(post)
    else:
        user.like_posts.add(post)

    return redirect("posts:index")
    

facebook/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  {% bootstrap_css %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'posts:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="">{{user.username}}<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃 <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:create' %}">글쓰기</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery="full" %}
</body>
</html>

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1>Index</h1>
  <div class="row">
    {% for post in posts %}
    <div class="card mx-2" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{post.user.username}}</h6>
        <p class="card-text">{{post.content}}</p>
        <p>{{post.like_users.all.count}}</p>
        <a href="{% url 'posts:like' post.id %}">
          <button type="button" class="btn btn-outline-primary">
            {% if user in post.like_users.all%}
              취소
            {% else %}
              좋아요
            {% endif %}
          </button>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}